version: '3.1'

services:
    db:
        container_name: speechsense-db
        image: postgres
        restart: always
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: password
            POSTGRES_DB: speechsense
        ports:
            - 5432:5432
    backend:
        image: node:18
        working_dir: /app
        volumes:
            - ./:/app
            - /app/node_modules
        command: sh -c "npm install && npm run start:dev"
        ports:
            - 8000:8000
        environment:
            DB_HOST: speechsense-db
            DB_PORT: 5432
            DB_USER: postgres
            DB_PASSWORD: password
            DB_NAME: speechsense
        depends_on:
            - db
